export const siteMetadata = {
  title: "Muhammad Fitrian Mubarok",
  description: "Muhammad Fitrian Mubarok Personal Portfolio",
  author: "Muhammad Fitrian Mubarok",
  siteUrl: "https://itsrian.my.id",
  language: "en",
  // Stored in public/og/og-image.png
  socialBanner: "/og/og-image.png",
  twitterBanner: "/og/og-image.png",
  favicon: "/favicon.ico",
  siteLogo: "/logo.png",
  image: "/og/og-image.png",
  email: "muhammadfitrianmubarok@gmail.com",
  github: "https://github.com/rianmubarok",
  twitter: "https://twitter.com/mub92253",
  facebook: "https://web.facebook.com/m.fitrian.37",
  youtube: "https://youtube.com/@rianmub",
  linkedin: "https://linkedin.com/in/rianmubarok",
  instagram: "https://instagram.com/m.fitrianm_/",
  locale: "en-US",
  analyticsURL: "https://analytics.itsrian.my.id",
  analytics: {
    plausibleDataDomain: "",
    simpleAnalytics: false,
    umamiWebsiteId: "",
    googleAnalyticsId: "",
    posthogAnalyticsId: "",
  },
  newsletter: {
    provider: "emailoctopus",
  },
  comments: {
    provider: "giscus",
    giscusConfig: {
      repo: "",
      repositoryId: "",
      category: "",
      categoryId: "",
      mapping: "",
      reactions: "1",
      metadata: "0",
      inputPosition: "top",
      lang: "en",
      darkTheme: "dark",
      themeURL: "",
    },
  },
  search: {
    provider: "kbar",
    kbarConfig: {
      searchDocumentsPath: "search.json",
    },
  },
};
