export const siteMetadata = {
  title: "Rian – Portfolio",
  description: "My Personal Portfolio",
  author: "Rian",
  siteUrl: "https://itsrian.com",
  language: "en",
  socialBanner: "/og-image.png",
  twitterBanner: "/og-image.png",
  favicon: "/favicon.ico",
  siteLogo: "/logo.png",
  image: "/og-image.png",
  email: "rian@example.com",
  github: "https://github.com/itsrian",
  twitter: "https://twitter.com/itsrian",
  facebook: "https://facebook.com/itsrian",
  youtube: "https://youtube.com/@itsrian",
  linkedin: "https://linkedin.com/in/itsrian",
  instagram: "https://instagram.com/itsrian",
  locale: "en-US",
  analyticsURL: "https://analytics.itsrian.com",
  analytics: {
    plausibleDataDomain: "",
    simpleAnalytics: false,
    umamiWebsiteId: "",
    googleAnalyticsId: "",
    posthogAnalyticsId: "",
  },
  newsletter: {
    provider: "emailoctopus",
  },
  comments: {
    provider: "giscus",
    giscusConfig: {
      repo: "",
      repositoryId: "",
      category: "",
      categoryId: "",
      mapping: "",
      reactions: "1",
      metadata: "0",
      inputPosition: "top",
      lang: "en",
      darkTheme: "dark",
      themeURL: "",
    },
  },
  search: {
    provider: "kbar",
    kbarConfig: {
      searchDocumentsPath: "search.json",
    },
  },
};
