import React, { JSX } from "react";
import { BsFillBootstrapFill, BsRobot } from "react-icons/bs";
import {
  SiAngular,
  SiApollographql,
  SiCss3,
  SiExpress,
  SiFirebase,
  SiGatsby,
  SiGraphql,
  SiJavascript,
  SiJest,
  SiJquery,
  SiLaravel,
  SiMui,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNuxtdotjs,
  SiPhp,
  SiPrisma,
  SiPwa,
  SiReact,
  SiRedux,
  SiSocketdotio,
  SiStorybook,
  SiStyledcomponents,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiVuedotjs,
  SiWebpack,
  SiWordpress,
  SiMongodb,
  SiGit,
  SiGithub,
  SiVercel,
  SiFigma,
  SiPostman,
  SiDocker,
  SiStripe,
  SiMysql,
  SiPostgresql,
  SiAmazon,
  SiGooglecloud,
  SiNetlify,
  SiSqlite,
  SiRailway,
  SiNotion,
  SiFlutter,
  SiDart,
} from "react-icons/si";

export type StackProps = {
  [key: string]: JSX.Element;
};

const iconSize = 20;

export const STACKS: StackProps = {
  PHP: <SiPhp size={iconSize} className="text-blue-500" />,
  JavaScript: <SiJavascript size={iconSize} className="text-yellow-400" />,
  TypeScript: <SiTypescript size={iconSize} className="text-blue-400" />,
  "Next.js": <SiNextdotjs size={iconSize} />,
  "React.js": <SiReact size={iconSize} className="text-sky-500" />,
  TailwindCSS: <SiTailwindcss size={iconSize} className="text-cyan-300" />,
  Bootstrap: (
    <BsFillBootstrapFill size={iconSize} className="text-purple-500" />
  ),
  // GraphQL: <SiGraphql size={iconSize} className="text-pink-600" />,
  Apollo: <SiApollographql size={iconSize} />,
  WordPress: <SiWordpress size={iconSize} />,
  Laravel: <SiLaravel size={iconSize} className="text-red-500" />,
  // "Material UI": <SiMui size={iconSize} className="text-sky-400" />,
  Vite: <SiVite size={iconSize} className="text-purple-500" />,
  // Prisma: <SiPrisma size={iconSize} className="text-emerald-500" />,
  Firebase: <SiFirebase size={iconSize} className="text-yellow-500" />,
  "Artificial Intelligence": (
    <BsRobot size={iconSize} className="text-rose-500" />
  ),
  // Angular: <SiAngular size={iconSize} className="text-red-500" />,
  "Vue.js": <SiVuedotjs size={iconSize} className="text-green-500" />,
  // "Nuxt.js": <SiNuxtdotjs size={iconSize} className="text-green-400" />,
  "Node.js": <SiNodedotjs size={iconSize} className="text-green-600" />,
  // Gatsby: <SiGatsby size={iconSize} className="text-purple-600" />,
  // Redux: <SiRedux size={iconSize} className="text-purple-500" />,
  // Webpack: <SiWebpack size={iconSize} className="text-blue-500" />,
  "Styled Components": (
    <SiStyledcomponents size={iconSize} className="text-pink-500" />
  ),
  // PWA: <SiPwa size={iconSize} className="text-amber-600" />,
  // Nginx: <SiNginx size={iconSize} className="text-green-500" />,
  // Jest: <SiJest size={iconSize} className="text-red-600" />,
  // Storybook: <SiStorybook size={iconSize} className="text-amber-500" />,
  CSS: <SiCss3 size={iconSize} className="text-blue-300" />,
  // Socket: <SiSocketdotio size={iconSize} />,
  // Express: <SiExpress size={iconSize} />,
  Jquery: <SiJquery size={iconSize} />,
  MongoDB: <SiMongodb size={iconSize} className="text-green-500" />,
  Git: <SiGit size={iconSize} className="text-orange-500" />,
  GitHub: <SiGithub size={iconSize} />,
  Vercel: <SiVercel size={iconSize} />,
  Figma: <SiFigma size={iconSize} className="text-pink-500" />,
  // Postman: <SiPostman size={iconSize} className="text-orange-500" />,
  // Docker: <SiDocker size={iconSize} className="text-blue-500" />,
  // Stripe: <SiStripe size={iconSize} className="text-blue-500" />,
  MySQL: <SiMysql size={iconSize} className="text-blue-500" />,
  // PostgreSQL: <SiPostgresql size={iconSize} className="text-blue-600" />,
  // AWS: <SiAmazon size={iconSize} className="text-orange-500" />,
  "Google Cloud": <SiGooglecloud size={iconSize} className="text-blue-500" />,
  // Netlify: <SiNetlify size={iconSize} className="text-green-500" />,
  Railway: <SiRailway size={iconSize} className="text-violet-500" />,
  Notion: <SiNotion size={iconSize} />,
  SQLite: <SiSqlite size={iconSize} className="text-blue-600" />,
  Dart: <SiDart size={iconSize} className="text-blue-600" />,
  Flutter: <SiFlutter size={iconSize} className="text-cyan-500" />,
}; 